version: '3.7'
services:
  app:
    container_name: devices-list-app
    image: murilo9/devices-list-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
